# Generated by Django 4.2.7 on 2023-11-06 15:15

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Secret',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_secret', models.CharField(max_length=20, verbose_name='name_secret')),
                ('secret', models.TextField(verbose_name='secret')),
                ('life_days', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1, message='Значение должно быть положительным.'), django.core.validators.MaxValueValidator(7, message='Количество дней жизни не может быть больше недели.')])),
                ('is_reader', models.BooleanField(default=False)),
                ('word_code', models.CharField(max_length=50, verbose_name='кодовое слово')),
                ('secret_key', models.CharField(blank=True, max_length=100, null=True, verbose_name='url тайны')),
                ('date_of_burning', models.DateTimeField(blank=True, null=True, verbose_name='дата сожжения секрета')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
